package com.laara.textnowcmp.core.util

data class Country(val name: String, val code: String, val flag: String)

val allCountries = listOf(
    Country("United States", "+1", "🇺🇸"),
    Country("United Kingdom", "+44", "🇬🇧"),
    Country("India", "+91", "🇮🇳"),
    Country("Canada", "+1", "🇨🇦"),
    Country("Australia", "+61", "🇦🇺"),
    Country("Germany", "+49", "🇩🇪"),
    Country("France", "+33", "🇫🇷"),
    Country("Brazil", "+55", "🇧🇷"),
    Country("Japan", "+81", "🇯🇵"),
    Country("China", "+86", "🇨🇳"),
    Country("South Korea", "+82", "🇰🇷"),
    Country("Mexico", "+52", "🇲🇽"),
    Country("Italy", "+39", "🇮🇹"),
    Country("Spain", "+34", "🇪🇸"),
    Country("Netherlands", "+31", "🇳🇱"),
    Country("Sweden", "+46", "🇸🇪"),
    Country("Norway", "+47", "🇳🇴"),
    Country("Denmark", "+45", "🇩🇰"),
    Country("Switzerland", "+41", "🇨🇭"),
    Country("Singapore", "+65", "🇸🇬"),
    Country("United Arab Emirates", "+971", "🇦🇪"),
    Country("Saudi Arabia", "+966", "🇸🇦"),
    Country("Pakistan", "+92", "🇵🇰"),
    Country("Bangladesh", "+880", "🇧🇩"),
    Country("Nigeria", "+234", "🇳🇬"),
    Country("South Africa", "+27", "🇿🇦"),
    Country("Kenya", "+254", "🇰🇪"),
    Country("Egypt", "+20", "🇪🇬"),
    Country("Turkey", "+90", "🇹🇷"),
    Country("Russia", "+7", "🇷🇺"),
    Country("Ukraine", "+380", "🇺🇦"),
    Country("Poland", "+48", "🇵🇱"),
    Country("Argentina", "+54", "🇦🇷"),
    Country("Colombia", "+57", "🇨🇴"),
    Country("Chile", "+56", "🇨🇱"),
    Country("Philippines", "+63", "🇵🇭"),
    Country("Indonesia", "+62", "🇮🇩"),
    Country("Malaysia", "+60", "🇲🇾"),
    Country("Thailand", "+66", "🇹🇭"),
    Country("Vietnam", "+84", "🇻🇳"),
    Country("New Zealand", "+64", "🇳🇿"),
    Country("Portugal", "+351", "🇵🇹"),
    Country("Greece", "+30", "🇬🇷"),
    Country("Israel", "+972", "🇮🇱"),
    Country("Ghana", "+233", "🇬🇭"),
    Country("Ethiopia", "+251", "🇪🇹"),
)
